Support arm64, update beepy-kbd and sharp-drm

diff --git a/beepy-kbd-2.11/debian/preinst b/beepy-kbd-2.11/debian/preinst
--- a/beepy-kbd-2.11/debian/preinst
+++ b/beepy-kbd-2.11/debian/preinst
@@ -15,6 +15,16 @@ if modprobe -n bbqX0kbd 2>/dev/null; then
 	exit 1
 fi
 
+# Check for swap size on arm64
+if [ "$(uname -m )" == "aarch64" ]; then
+	. /etc/dphys-swapfile
+	if (( CONF_SWAPSIZE < 512 )); then
+		echo "error: CONF_SWAPSIZE detected as $CONF_SWAPSIZE"
+		echo "Please edit /etc/dphys-swapfile, increase to at least 512, and reboot"
+		exit 1
+	fi
+fi
+
 # Get firmware version
 
 # Available from driver
